### PR TITLE
Initial set of tests for DSC parameter estimation

### PR DESCRIPTION
**Pull request by JonathanArvidsson**
Some initial tests for DSC parameter estimation. 

There are some changes in the files from Sudarshan and Laura and I'd like them to check that they agree on this.

1. In AIF_deconvolution, there are two rows in the end of the file, which were left out, but are necessary to obtain the residue function. These were copied from the jupyter notebook pipeline and makes the test code much cleaner. I hope you agree. 

2. In DSC_parameters.py where I removed '/TR' for the cbf parameter. 

PM me on slack to discus these, I want to make sure that I haven't misunderstood anything and to hear if you agree with the suggestions. :)   

Jonathan

### CODE REVIEW

**Comment by JonathanArvidsson** [comment]
Build machine probably needs to have nibabel package installed to load the DRO data which is saved as .nii.

**Comment by sudarshanragu** [comment]
Thanks for adding the missing lines  of code @JonathanArvidsson !

**Comment by mjt320** [comment]
Hi @JonathanArvidsson @schudds
Thanks for the additional code + tests. This is a great addition to the project.
A few comments/suggestions:

Delay parameter is documented as bool but default is numeric

It would be useful to note units of parameters as comments, e.g. cbf_w

Maybe I misunderstood the code, but I think you're looping through test cases within the test function. The @parametrize decorator should do this for you so that each case is an independent test that can fail or pass. At the moment all of your cases are running as a single test.
If you click through to the CI/build details above you'll see this. You'll also notice a few warnings associated with the DSC tests.

It's not immediately obvious to the user what the test cases are, i.e. what parameter combinations are being tested. Could they be described/listed somewhere?
One suggestion: convert all relevant data to a human-readable CSV. This code only has to be run once and we don't have to re-read the .nii and .mat files every time a test is run. dsc_DRO_data_vascular_model then just reads the CSV each time.

Hope that helps.

**Comment by JonathanArvidsson** [comment]
Thanks, good points. I'll look into your suggestions in more detail when I have a moment and get back to you via slack If further clarifications is needed. :)

**Comment by JonathanArvidsson** [comment]
I've addressed most (if not all) suggestions from @mjt320. As of this the include for nibabel can be removed @notZaki

**Comment by mjt320** [comment]
Thanks @JonathanArvidsson 
This looks good to me!

**Comment by petravanhoudt** [comment]
Hi @JonathanArvidsson, I've added a notebook on the CBF and CBV estimation. Could you carefully check the notebook and add relevant information? [DCE-DSC-MRI_CodeCollection](https://github.com/OSIPI/DCE-DSC-MRI_CodeCollection/tree/DSC_tests_LcurveReg)/[notebooks](https://github.com/OSIPI/DCE-DSC-MRI_CodeCollection/tree/DSC_tests_LcurveReg/notebooks)/DSC_pars.ipynb)

**Comment by mjt320** [comment]
The notebooks look good @petravanhoudt 
Under Test Data, suggest to add units for TR and TE.

**Comment by petravanhoudt** [comment]
@JonathanArvidsson, before we finish this merge, can you 
- check the units of TR/TE in the test data description?
- was there any background info you wanted to add?
thanks!

**Comment by JonathanArvidsson** [comment]
Background changes:

- I added some info in regard to the AIF function, but rather than going into more detail, I think we should encourage the reader to read the original article..

- Checked units (good call there). 

- Restructured slightly, feel free to change accordingly if it does not align with other notebooks.

**Comment by petravanhoudt** [comment]
Thanks! the pull request is finished

**Pull request merged**
