### PR TITLE
Dc emodels test

### PR DESCRIPTION
**Pull request by oliverchampion**
Implemented unit testing for Tofts and Extended Tofts models.

### CODE REVIEW

**Comment by notZaki** [comment]
I tried to add some missing dependencies, but tests are still failing because TkAgg is used at some point.

**Comment by oliverchampion** [comment]
I commented the TkAgg line from the code (was in the OGJ_OsloU_Norway.MRImagaAnalysis.MRImage.py code. 
It now seems to fail some of the pytests online, which it does not fail locally...

**Comment by notZaki** [comment]
It looks like the `append_to_excel` function was having issues. I tried re-arranging it and the tests now run, but not sure if all the functionality was retained. :shrug:

**Comment by oliverchampion** [comment]
Hey! I think the append-to-excel function was written by Sirisham but was only requiered for the ISMRM abstract. If it fails the tests, I think we can probably remove it?!

**Comment by petravanhoudt** [comment]
> Hey! I think the append-to-excel function was written by Sirisham but was only requiered for the ISMRM abstract. If it fails the tests, I think we can probably remove it?!

Yes I think so too

**Comment by notZaki** [comment]
The tests are passing now. The only failing check is the code coverage, but that should be fine.
So it isn't necessary to remove the `append_to_excel` function, but it could still be removed if it is no longer necessary.

**Comment by petravanhoudt** [comment]
Hi @oliverchampion and @stadmill, 

A few minor comments so far. 
The prostate data are not used anymore for the tests, isn't it? It might be better to remove them from dce_data.py.
For consistency I would rename the dce_DRO_data, to indicate the model used.

**Comment by oliverchampion** [comment]
@petravanhoudt done :)

**Review by mjt320 — COMMENTED** [review]
Thanks for your hard work @oliverchampion, @stadmill !
In dce_data.py : please could you update the docstrings to describe the tests/data?
Suggest the function names in the above module should reflect the data sources + models
Some of the modules contain many commented lines - can we remove?
One of the test function in the OGJ module is named LEK
It's unclear why various test cases are excluded for each contribution
In the CSV data files, I suggest putting the parameter columns next to the labels column, to make it more readable for the user
Happy to chat about this...

**Comment by oliverchampion** [comment]
Does anything else need doing for this pull request? I don't fully know how to address the code coverage issue :).

**Comment by mjt320** [comment]
Hi @oliverchampion. See my comments above. I don't think that the codecov issue is a problem.

**Comment by oliverchampion** [comment]
Hey @mjt320,

I think I now addressed all your remarks in the new update :). Thanks for going through our code in detail!

Cheers!

Oliver

**Comment by mjt320** [comment]
Hi @oliverchampion and @stadmill (CC @petravanhoudt)
Thanks for improving the tests. I made a few minor changes and tidied further:
- rename test files to include "DCEmodels"
- removed plot/print lines
- changed tolerance for arterial delay to temporal resolution/2 -- previous values of 0.01/0.03 s are too small IMO and some tests were failing
- uncommented arterial delay assertion in LEK test file
Hope that's okay.

Please could you check a few more things...
1. could the meaning of the test "labels" be documented, e.g. test_vox_T2_20_delayed - not sure what the "20" is, for example
2. GM/WM/VIF voxels are mentioned in the docstrings, but I don't think they are used(?)
3. I couldn't work out what setting delay=True does and the "arterial delay" values in the CSV files are all zero. Could this be explained somewhere? Sorry if I'm being daft.
4. one test of LEK's code is failing on vP - not sure why as everything passed for the ISMRM abstract

Thanks, Michael

**Pull request merged**
