### PR TITLE
add code contribution

### PR DESCRIPTION
**Pull request by sudarshanragu**
@mjt320 , @petravanhoudt Should we keep the data file required to run the Jupyter Notebook or remove it from the develop branch but keep it in LCB_CodeContribution?

### CODE REVIEW

**Comment by mjt320** [comment]
I would be inclined to keep it with the notebook so that anyone finding the notebook can run it easily(?)

**Comment by fedorov** [comment]
The notebook is titled "Chapter 13" - what is the origin of this contribution, and are other chapters available?

**Comment by sudarshanragu** [comment]
@fedorov This was a notebook originally created as supplementary material for a book on neuroimaging techniques and Chapter 13  pertains to perfusion techniques.

**Review by mjt320 — COMMENTED** [review]
Hi @schudds I'm happy for you to merge this contribution.
One comment: the notebook is really nice and educational. I personally think it would be good to also put the code in a module (when we have time), so that other users can easily re-use the code. What do you think, @petravanhoudt ?

**Comment by sudarshanragu** [comment]
@mjt320 sounds good. I can continue to add the code from the notebook as functions on my branch (just like I did with the leakage correction, as it is all the same code). It shouldn't take long.

**Pull request merged**
