### PR TITLE
AIF Deconvolution

### PR DESCRIPTION
**Pull request by sudarshanragu**
Added code to perform AIF deconvolution using Voltera discretization and L-curve regularization.

### CODE REVIEW

**Comment by mjt320** [comment]
Hi @schudds . Just wondering if this pull request is ready for review and merging?

**Comment by sudarshanragu** [comment]
@mjt320 I think the codecov fail stems from this branch not being fast forwarded to develop. Otherwise, I think this is ready for review.

**Review by mjt320 — APPROVED** [review]
I think we can merge. What do you think, @petravanhoudt

**Review by petravanhoudt — APPROVED** [review]
I agree with @mjt320, I also see no reason for changes. Thanks for this extra contribution @schudds!

**Pull request merged**
