### PR TITLE
Population aif test

### PR DESCRIPTION
**Pull request by petravanhoudt**
The tests for population AIFs (Parker and Georgiuo) are added.

The reference data consists of:
- original published AIFs (with original temp resolution)
- different temporal resolutions
- shifted AIFs 

Do you have suggestions for extensions of the reference data?

instead of creating a csv file with the reference data, I decided to create the testdata in the popAIF_data directly, as I found myself writing a python script to create a csv file and later opening this csv file. So that seemed not as effcient. @mjt320 do you think this is accetable?

to do: 
- write test for modified Parker AIF of ST_SydneyAus, which allows for different injection durations
- write test for preclinical AIF of ST_SydneyAus

### CODE REVIEW

**Comment by petravanhoudt** [comment]
@mjt320 Am I right in assuming that the tstart from aifs.py assumes the value to be similar to the temporal resolution?

**Comment by petravanhoudt** [comment]
Aha, I see that there is a package missing to open the xls file as is needed to create the reference data. How do I add such a package in ci? @schudds @mjt320

**Comment by mjt320** [comment]
> @mjt320 I am right in assuming that the tstart from aifs.py assumes the value to be similar to the temporal resolution?

No, it does not have to be

**Comment by mjt320** [comment]
> Aha, I see that there is a package missing to open the xls file as is needed to create the reference data. How do I add such a package in ci? @schudds @mjt320

I think you just add to the list in setup.py

**Comment by petravanhoudt** [comment]
> > @mjt320 I am right in assuming that the tstart from aifs.py assumes the value to be similar to the temporal resolution?
> 
> No, it does not have to be

Ok maybe we should have a look together why the test fails for some of the cases. But that is not really urgent for now.

**Comment by petravanhoudt** [comment]
> > Aha, I see that there is a package missing to open the xls file as is needed to create the reference data. How do I add such a package in ci? @schudds @mjt320
> 
> I think you just add to the list in setup.py

ok thanks, this fixed it :+1:

**Comment by mjt320** [comment]
> > > @mjt320 I am right in assuming that the tstart from aifs.py assumes the value to be similar to the temporal resolution?
> > 
> > 
> > No, it does not have to be
> 
> Ok maybe we should have a look together why the test fails for some of the cases. But that is not really urgent for now.

My code calculates C using the Parker equation at the delayed time values, so it should work with any delay value.
I think that yours and ST's codes calculate the C for zero delay, then right-shift the vector by an integer number of dt.

**Comment by mjt320** [comment]
> instead of creating a csv file with the reference data, I decided to create the testdata in the popAIF_data directly, as I found myself writing a python script to create a csv file and later opening this csv file. So that seemed not as effcient. @mjt320 do you think this is accetable?

IMO, it would be better for the reference data to be supplied as a CSV file. This means the reference data is (a) fixed and (b) easily readable. At the moment, in theory, a change in the python environment (e.g. package update) could change both the reference data and the behaviour of the tested functions, which would be confusing. You can include the script for generating the CSV if it's not available elsewhere.

I suggest the tolerances (currently 0.05 mM + 5%) could be much smaller for these tests.

**Comment by petravanhoudt** [comment]
> > instead of creating a csv file with the reference data, I decided to create the testdata in the popAIF_data directly, as I found myself writing a python script to create a csv file and later opening this csv file. So that seemed not as effcient. @mjt320 do you think this is accetable?
> 
> IMO, it would be better for the reference data to be supplied as a CSV file. This means the reference data is (a) fixed and (b) easily readable. At the moment, in theory, a change in the python environment (e.g. package update) could change both the reference data and the behaviour of the tested functions, which would be confusing. You can include the script for generating the CSV if it's not available elsewhere.
> 
> I suggest the tolerances (currently 0.05 mM + 5%) could be much smaller for these tests.

Ok yes, I can change it as you suggested

**Comment by petravanhoudt** [comment]
Tests have been updated:
- data has been saved as csv file (python file to generate test data is included as well) 
- modified test data for delay in Parker AIF to test both a shift and recalculated AIF
- updated tolerance levels + fixed error in tol levels
- added tests for preclinical AIF

still to do: add test for OG_MO_AUMC_ICR_RMH (Parker + head-and-neck population AIF)

**Review by mjt320 — CHANGES_REQUESTED** [review]
Thanks for all this work, @petravanhoudt ! Just a couple of comments...
Can PopulationAIF_ParkerMRM2006.txt be removed?
For Parker + delay, I think you've effectively used different reference data for different contributions. I would still argue that time-shifting by the nearest number of dt is an approximation (due to the rounding), therefore it's not appropriate for reference data. What do you think?

**Comment by petravanhoudt** [comment]
> Thanks for all this work, @petravanhoudt ! Just a couple of comments... Can PopulationAIF_ParkerMRM2006.txt be removed? For Parker + delay, I think you've effectively used different reference data for different contributions. I would still argue that time-shifting by the nearest number of dt is an approximation (due to the rounding), therefore it's not appropriate for reference data. What do you think?

Hi @mjt320, 
txt file has been removed as you suggested.

I've updated the delay data by removing the shifts and only having the recalculated concentration values. For the ST contribution I added a comment that some of the test data fail because of a different implementation (i.e. shift of concentration values to nearest number of dt). For all other contributions this works fine.

Ready to merge with develop, do you think?

**Review by mjt320 — APPROVED** [review]

**Comment by mjt320** [comment]
Hi @petravanhoudt. Yes, I think it can be merged.

**Review by mjt320 — APPROVED** [review]

**Pull request merged**
