### PR TITLE
New pk model tests

### PR DESCRIPTION
**Pull request by mjt320**
added tests for 2CXM, 2CUM and Patlak DCE models
made tests with/without artery-capillary delay separate

### CODE REVIEW

**Comment by mjt320** [comment]
Please also note changes to the tolerances

**Comment by petravanhoudt** [comment]
Hi @mjt320 

thanks for completing this.
Two thoughts:
- did we want to add the NLLS fitting for the OGJ contribution next to the LLSQ fitting method?
- I would suggest we first merge demo with the develop branch and afterwards merge this one with develop.

**Comment by mjt320** [comment]
> * did we want to add the NLLS fitting for the OGJ contribution next to the LLSQ fitting method?
Done. Thanks for reminder!
> * I would suggest we first merge demo with the develop branch and afterwards merge this one with develop.
Okay

**Comment by petravanhoudt** [comment]
I have fixed some merge issues with the test files. The notebooks and json file still need to be udpated before we can perform the merge to develop

**Comment by petravanhoudt** [comment]
Updates on the notebooks based on the new tests for DCE models:
- added notebook for 2CUM and 2CXM
- split test results for delayed and non-delayed data
- separated the NLLS and LLSQ results for the contribution by OGJ_OsloU_Norway

**Pull request merged**
