### PR TITLE
add categorical plot for etofts

### PR DESCRIPTION
**Pull request by mjt320**
Plot idea for the paper, as discussed @petravanhoudt

### CODE REVIEW

**Comment by petravanhoudt** [comment]
the labelling on the x-axis in the figure is not correct yet, will change this later

**Comment by petravanhoudt** [comment]
update:
- fixed the x-axis in the Ktrans plot of the eTofts model
- added figure for ve
- added similar figures in the Tofts notebook

@mjt320 Once we agree about these graphs, we can remove the older figures to reduce clutter. 
Can the BA statistics be removed as well?
I will make an issue to add similar plots to other model notebooks

possible future improvements: 
- add the non-delayed results in the same figure but with a different marker, to prevent too many figures in the notebook?

**Comment by mjt320** [comment]
> @mjt320 Once we agree about these graphs, we can remove the older figures to reduce clutter. Can the BA statistics be removed as well? I will make an issue to add similar plots to other model notebooks

I suppose so. We don't use them in the paper.

> * add the non-delayed results in the same figure but with a different marker, to prevent too many figures in the notebook?

Yes, could add them as a different test case/x-category (not sure if that's what you meant)
Not urgent, though.

**Comment by petravanhoudt** [comment]
removed old BA plots
added similar figures for all model notebooks

There are a lot of figures now, which could probably be improved. See issue to deal with this later #97

**Pull request merged**
