### PR TITLE
Added testing for SI to concentration functions

### PR DESCRIPTION
**Pull request by LucyKershaw**

### CODE REVIEW

**Review by mjt320 — COMMENTED** [review]
Hi Lucy. Thanks so much for doing this. Looks great.
A few minor comments:
- Absolute tolerance of 0.001 mM might be a bit high for less vascular tissues, e.g. brain [CA] can be around 0.005 mM.
- Getting to the bottom of the 150 curves thing would be helpful for users! Maybe the function handles multiple time series, so you might need to input a 2D signal matrix (with one singleton dimension). Otherwise, I'm sure OG would be happy to help.
- We're comparing the entire curve, so if one value is wrong then the test fails. Think that's okay as long as all the code works.
- Is there a relevant link/citation for the UoE code (even a publication that mentions it)?
- To avoid the use of fake flip angles etc. I'd be happy to add some voxels from a brain study?

Thanks again.

**Comment by mjt320** [comment]
Thanks Lucy.
Looks good to me.
I've deleted the ds_store files, pyc files and __pychache__ folders, and amended .gitignore so that they are ignored in future.
@petravanhoudt please go ahead and merge if you're also happy

**Review by petravanhoudt — COMMENTED** [review]
Hi @LucyKershaw, thanks for doing this! It looks great.

Two comments:
- there are a few more contributions with S to C functionality (see database at the develop branch). Could those also be added?
- I was wondering whether the test data set should be extended with other examples? This is more a general question probably, but how much data would we need to test these functions? We could think of adding the DRO data of the DCE challenge task force when it becomes available.

**Comment by LucyKershaw** [comment]
Hi Petra,

I'm so sorry - where am I looking for the database? I see that lots of extra folders of original code have appeared since I first did this!

I thought for a long time about including more examples, but decided in the end that for such a simple function it's hard to imagine a situation where one curve would work for the conversion but another wouldn't.  There would have to be something very strange going on.  For something like curve fitting that is much more complex I can certainly see the benefit of testing lots of cases, but here I think we're pretty much just checking for an error in the code so a small number of reasonable cases seems appropriate to me.

Obviously if the consensus is that more are needed then I'm happy to include them.

**Comment by mjt320** [comment]
I can see both points. I'd be happy to add more test data after the merge. It won't take long.
A couple of further thoughts
- I submitted some code that takes a numerical approach (so that it is generalisable to any sequence), so it is not 100% precise
- If we include [Gd] dependence of R2* then we need a numerical solution I think - not sure how widespread this is and how many of the contributions allow for it?

**Pull request merged**
